DROP FUNCTION IF EXISTS FN_TRANSFORM_NOTES_RATE;
CREATE FUNCTION FN_TRANSFORM_NOTES_RATE(PARAM_RATE DOUBLE(20, 6)) RETURNS VARCHAR(32)

BEGIN 

  DECLARE V_RATE_STRING VARCHAR(32);
  DECLARE V_DOT_LOCATION INT;

  -- 小数点后面的位数
  DECLARE V_DIGITAL_LENGTH_AFTER_DOT INT;

  SET V_RATE_STRING = 0 + CAST(PARAM_RATE AS CHAR);

  IF ( POSITION('.' IN V_RATE_STRING) ) THEN

    SET V_DOT_LOCATION = POSITION('.' IN V_RATE_STRING);

    SET V_DIGITAL_LENGTH_AFTER_DOT = LENGTH( SUBSTRING(V_RATE_STRING, V_DOT_LOCATION + 1) );

    IF (V_DIGITAL_LENGTH_AFTER_DOT < 2) THEN
      -- SET V_RATE_STRING = FORMAT(V_RATE_STRING, 2); -- 满三位会加一个逗号
      SET V_RATE_STRING = CONVERT(V_RATE_STRING, DECIMAL(12, 2) );
    END IF;

  ELSE

    -- SET V_RATE_STRING = FORMAT(V_RATE_STRING, 2);
    SET V_RATE_STRING = CONVERT(V_RATE_STRING, DECIMAL(12, 2) );
  END IF;

  RETURN V_RATE_STRING;
END;