DROP PROCEDURE IF EXISTS SP_AUDIT_CONTRACT_RATE_BY_QUANTITY;
CREATE  PROCEDURE `SP_AUDIT_CONTRACT_RATE_BY_QUANTITY`(
  IN PARAM_REFERENCE_ID INT,
  IN PARAM_QUANTITY INT(32),
  IN PARAM_PROPOSAL_ID INT,
  OUT PARAM_EXPECT_RATE DOUBLE,
  OUT PARAM_NOTES VARCHAR ( 768 ),
  OUT PARAM_RATE_EFFECTIVE_DATE DATE
)
BEGIN

  DECLARE V_REFERENCE_ID INT;

  SELECT c.id INTO V_REFERENCE_ID
  FROM
    contract_rate_by_quantity c
  WHERE
    c.contract_id = PARAM_REFERENCE_ID
    AND c.quantity_begin <= PARAM_QUANTITY
    AND (c.quantity_end >= PARAM_QUANTITY OR c.quantity_end IS NULL);

  CALL SP_GET_RATE_KEY_FIELDS(
    'contract_rate_by_quantity',
    V_REFERENCE_ID,
    PARAM_PROPOSAL_ID,
    PARAM_EXPECT_RATE,
    PARAM_RATE_EFFECTIVE_DATE
  );
    
  IF PARAM_EXPECT_RATE IS NOT NULL THEN

      SET PARAM_NOTES = CONCAT(
        'The rate is $', 
        FN_TRANSFORM_NOTES_RATE(PARAM_EXPECT_RATE) , 
        ', The Quantity of SIP Sessions is ', 
        PARAM_QUANTITY, 
        '.'
      );
      
  END IF;

END