INSERT INTO `audit_key_field` VALUES (2, 'Y', 2, 'Item Description & SVN', 'item_description', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (3, 'Y', 2, 'Item Description & SVN & Qty', 'item_description', 'tariff_rate_by_quantity', 'tariff_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (4, 'Y', 2, 'Item Type & SVN', 'usage_item_type', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (5, 'Y', 2, 'Item Type & SVN & VN', 'usage_item_type', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (6, 'Y', 2, 'Line Item Code', 'line_item_code', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (7, 'Y', 2, 'Line Item Code & SVN', 'line_item_code', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (8, 'Y', 2, 'Line Item Code & SVN & Discount', 'line_item_code', 'tariff_rate_discount', 'tariff');
INSERT INTO `audit_key_field` VALUES (9, 'Y', 2, 'Line Item Code & SVN & Multiplier', 'line_item_code', 'tariff_rate_multiplier', 'tariff');
INSERT INTO `audit_key_field` VALUES (10, 'Y', 2, 'Line Item Code & SVN & Qty', 'line_item_code', 'tariff_rate_by_quantity', 'tariff_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (11, 'Y', 2, 'Line Item Code & SVN & VN', 'line_item_code', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (12, 'Y', 2, 'Line Item Code & SVN & VN & Discount', 'line_item_code', 'tariff_rate_discount', 'tariff');
INSERT INTO `audit_key_field` VALUES (13, 'Y', 2, 'Line Item Code Description & SVN', 'line_item_code_description', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (14, 'Y', 2, 'Line Item Code Description & SVN & VN', 'line_item_code_description', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (15, 'Y', 2, 'USOC', 'usoc', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (16, 'Y', 2, 'USOC & SVN', 'usoc', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (17, 'Y', 2, 'USOC & SVN (Max rate)', 'usoc', 'rate_max', 'tariff');
INSERT INTO `audit_key_field` VALUES (18, 'Y', 2, 'USOC & SVN & Qty', 'usoc', 'tariff_rate_by_quantity', 'tariff_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (19, 'Y', 2, 'USOC & SVN & Qty (Max rate)', 'usoc', 'tariff_rate_by_quantity_rate_max', 'tariff_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (20, 'Y', 2, 'USOC & SVN & Qty + Base Amount', 'usoc', 'tariff_rate_by_quantity_base_amount', 'tariff_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (21, 'Y', 2, 'USOC & SVN & VN', 'usoc', 'rate', 'tariff');
INSERT INTO `audit_key_field` VALUES (22, 'Y', 2, 'USOC & SVN & VN & Qty', 'usoc', 'tariff_rate_by_quantity', 'tariff_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (23, 'Y', 2, 'USOC & SVN (Either Rate)', 'usoc', 'rate_any', 'tariff');
INSERT INTO `audit_key_field` VALUES (24, 'Y', 3, 'Stripped Circuit Number', 'stripped_circuit_number', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (25, 'Y', 3, 'Stripped Circuit Number & Item Description', 'stripped_circuit_number & item_description', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (26, 'Y', 3, 'Stripped Circuit Number & Item Description & SVN', 'stripped_circuit_number & item_description', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (27, 'Y', 3, 'Stripped Circuit Number & Line Item Code', 'stripped_circuit_number & line_item_code', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (28, 'Y', 3, 'Stripped Circuit Number & Line Item Code Description', 'stripped_circuit_number & line_item_code_description', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (29, 'Y', 3, 'Stripped Circuit Number & SVN', 'stripped_circuit_number', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (30, 'Y', 3, 'USOC & Stripped Circuit Number', 'usoc & stripped_circuit_number', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (31, 'Y', 3, 'USOC & Stripped Circuit Number & SVN', 'usoc & stripped_circuit_number', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (32, 'Y', 3, 'Item Description & SVN', 'item_description', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (33, 'Y', 3, 'Item Description & SVN & Qty', 'item_description', 'contract_rate_by_quantity', 'contract_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (34, 'Y', 3, 'Line Item Code', 'line_item_code', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (35, 'Y', 3, 'Line Item Code & SVN', 'line_item_code', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (36, 'Y', 3, 'Line Item Code & SVN & Qty', 'line_item_code', 'contract_rate_by_quantity', 'contract_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (38, 'Y', 3, 'Line Item Code Description & SVN', 'line_item_code_description', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (40, 'Y', 3, 'USOC', 'usoc', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (41, 'Y', 3, 'USOC & SVN', 'usoc', 'rate', 'contract');
INSERT INTO `audit_key_field` VALUES (42, 'Y', 3, 'USOC & SVN (Max rate)', 'usoc', 'rate_max', 'contract');
INSERT INTO `audit_key_field` VALUES (43, 'Y', 3, 'USOC & SVN & Qty', 'usoc', 'contract_rate_by_quantity', 'contract_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (46, 'Y', 3, 'USOC & SVN (Either Rate)', 'usoc', 'rate_any', 'contract');
INSERT INTO `audit_key_field` VALUES (47, 'Y', 3, 'Line Item Code Description & SVN & CVPP', 'cvpp', 'cvpp', 'contract');
INSERT INTO `audit_key_field` VALUES (48, 'Y', 18, 'Stripped Circuit Number', 'stripped_circuit_number', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (49, 'Y', 18, 'Stripped Circuit Number & Item Description', 'stripped_circuit_number & item_description', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (50, 'Y', 18, 'Stripped Circuit Number & Item Description & SVN', 'stripped_circuit_number & item_description', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (51, 'Y', 18, 'Stripped Circuit Number & Line Item Code', 'stripped_circuit_number & line_item_code', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (52, 'Y', 18, 'Stripped Circuit Number & Line Item Code Description', 'stripped_circuit_number & line_item_code_description', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (53, 'Y', 18, 'Stripped Circuit Number & SVN', 'stripped_circuit_number', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (54, 'Y', 18, 'USOC & Stripped Circuit Number', 'usoc & stripped_circuit_number', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (55, 'Y', 18, 'USOC & Stripped Circuit Number & SVN', 'usoc & stripped_circuit_number', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (56, 'Y', 18, 'Item Description & SVN', 'item_description', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (57, 'Y', 18, 'Line Item Code', 'line_item_code', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (58, 'Y', 18, 'Line Item Code & SVN', 'line_item_code', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (60, 'Y', 18, 'Line Item Code Description & SVN', 'line_item_code_description', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (62, 'Y', 18, 'USOC', 'usoc', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (63, 'Y', 18, 'USOC & SVN', 'usoc', 'rate', 'audit_mtm');
INSERT INTO `audit_key_field` VALUES (65, 'Y', 2, 'Item Description & SVN & Qty + Base Amount', 'item_description', 'tariff_rate_by_quantity_base_amount', 'tariff_rate_by_quantity');
INSERT INTO `audit_key_field` VALUES (66, 'N', 3, 'USOC & SVN & CVPP', 'cvpp', 'cvpp', 'contract');
INSERT INTO `audit_key_field` VALUES (67, 'N', 3, 'Line Item Code & SVN & CVPP', 'cvpp', 'cvpp', 'contract');
INSERT INTO `audit_key_field` VALUES (68, 'N', 3, 'Item Description & SVN & CVPP', 'cvpp', 'cvpp', 'contract');
